name: Profile Readme Development Stats

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # SYMBOL_VERSION : 3
          # SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"

          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "False"
          SHOW_PROJECTS: "True"
          SHOW_OS: "False"
          
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"

          # SHOW_UPDATED_DATE: "False"

# 'SECTION_NAME', 'PULL_BRANCH_NAME', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 
# 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'SHOW_UPDATED_DATE', 'SHOW_TOTAL_CODE_TIME', 'COMMIT_BY_ME', 
# 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'COMMIT_SINGLE', 'LOCALE', 'UPDATED_DATE_FORMAT', 'IGNORED_REPOS', 'SYMBOL_VERSION', 'DEBUG_LOGGING'
